In [1]:
import numpy as np

In [2]:
from keras.models import Sequential
from keras.layers import SimpleRNN, Masking
import keras.backend as K

Using Theano backend.
/home/budmitr/anaconda/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")


In [92]:
X = np.array([
    [[1, 1, 1], [2, 2, 2], [-1, -1, -1], [-1, -1, -1], [-1, -1, -1]],
    [[4, 4, 4], [-1, -1, -1], [-1, -1, -1], [-1, -1, -1], [-1, -1, -1]]
  ]).astype(np.float32)

X1 = np.array([
    [[1, 1, 1], [2, 2, 2], [-1, -1, -1], [-1, -1, -1]],
    [[4, 4, 4], [-1, -1, -1], [-1, -1, -1], [-1, -1, -1]]
  ]).astype(np.float32)

X2 = np.array([
    [[1, 1, 1], [2, 2, 2], [-1, -1, -1]],
    [[4, 4, 4], [-1, -1, -1], [-1, -1, -1]]
  ])

X3 = np.array([
    [[1, 1, 1], [2, 2, 2]],
    [[4, 4, 4], [-1, -1, -1]]
  ])

In [94]:
np.random.seed(0)
model = Sequential()
model.add(Masking(-1, input_shape=(5,3)))
model.add(SimpleRNN(1, activation='linear', input_shape=(5,3)))
model.compile(optimizer='sgd', loss='mae')

In [95]:
print model.predict(X)
print
print model.predict(X1)
print
print model.predict(X2)
print
print model.predict(X3)

[[ 3.6088047 ]
 [ 4.65652227]]

[[ 3.6088047 ]
 [ 4.65652227]]

[[ 3.6088047 ]
 [ 4.65652227]]

[[ 3.6088047 ]
 [ 4.65652227]]


In [91]:
print model.predict(X)
print
print model.predict(X1)
print
print model.predict(X2)
print
print model.predict(X3)

[[-2.07339478]
 [ 5.45987654]]

[[ 1.06818604]
 [-5.78024244]]

[[-1.7877965 ]
 [ 4.43804741]]

[[ 0.80855113]
 [-4.85130692]]


In [12]:
getmask = K.function([model.layers[0].get_input()], [model.layers[0].get_output_mask()])

In [24]:
getmask([X])

[array([[1, 1, 0],
        [1, 0, 0]], dtype=int8)]